export default {
  ACCOUNT_STORE_NAME          : 'salesInfo',
  GET_USER_INFO_SUCCESS       : 'GET_USER_INFO_SUCCESS',
  GET_USER_INFO_FAILED        : 'GET_USER_INFO_FAILED',
  SAVE_USER_INFO_SUCCESS      : 'SAVE_USER_INFO_SUCCESS',
  SAVE_USER_INFO_FAILED       : 'SAVE_USER_INFO_FAILED',
};
